### ISSUE TITLE
Uncertain calculations on empty DataFrame / Series

### ISSUE THREAD

**Issue by meliache** [nils-braun/uncertain_panda#2]
```python
from uncertain_panda import pandas as upd
upd.DataFrame([]).unc.mean()
```
returns an empty data frame again. This seems similar to the normal mean method (without `.unc`) which returns an empty series. However, calculating the uncertain mean on an empty series throws a `ValueError`:
```python
upd.Series([]).unc.mean()
```
See the [full traceback](https://github.com/nils-braun/uncertain_panda/files/3368357/empty_series_unc_mean_error.txt). It comes from trying to bootstrapping an empty series, which obviously does not make sense, so the `rs.choice` method fails. 

I would suggest to make it return `nan` instead, to keep it consistent with `pd.Series([]).mean()` etc, either by wrapping it in another `try...except ValueError` and/or doing an `if` check for empty Series.

**Comment by nils-braun** [comment]
Thanks for the issue. I have seen your use case in the Belle II example and I am with you.
Although from a conceptional point of view it makes sense to throw an exception, because what should be the statistical uncertainty of an empty measurement set? Anyways, returning nan is probably reasonable. I will implement it.

**Comment by nils-braun** [comment]
Please reopen in case the PR has not solved the issue.
